// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⭐ WEB
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDbVsnO6ePNYn_X5DHLnovOdKlk0efmQk',
    appId: '1:691945279842:web:520b29ff9c7cf557511c3b',
    messagingSenderId: '691945279842',
    projectId: 'paceo-f6257',
    authDomain: 'paceo-f6257.firebaseapp.com',
    storageBucket: 'paceo-f6257.appspot.com', // ✔ FIXED
    measurementId: 'G-QGW2DR0QFC',
  );

  // ⭐ ANDROID
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcTR_SE1cvEr3MlgA-GhMPws-nNy6ddnM',
    appId: '1:691945279842:android:785049a9b79d688e511c3b',
    messagingSenderId: '691945279842',
    projectId: 'paceo-f6257',
    storageBucket: 'paceo-f6257.appspot.com', // ✔ FIXED
  );

  // ⭐ IOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBn7r5XQoZJkQKRuOz6gkuRcnZ8HyGX-M',
    appId: '1:691945279842:ios:c84255a433408929511c3b',
    messagingSenderId: '691945279842',
    projectId: 'paceo-f6257',
    storageBucket: 'paceo-f6257.appspot.com', // ✔ FIXED
    iosBundleId: 'com.example.paceo',
  );

  // ⭐ macOS
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBn7r5XQoZJkQKRuOz6gkuRcnZ8HyGX-M',
    appId: '1:691945279842:ios:c84255a433408929511c3b',
    messagingSenderId: '691945279842',
    projectId: 'paceo-f6257',
    storageBucket: 'paceo-f6257.appspot.com', // ✔ FIXED
    iosBundleId: 'com.example.paceo',
  );

  // ⭐ WINDOWS
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDbVsnO6ePNYn_X5DHLnovOdKlk0efmQk',
    appId: '1:691945279842:web:119b9a474cf62dda511c3b',
    messagingSenderId: '691945279842',
    projectId: 'paceo-f6257',
    authDomain: 'paceo-f6257.firebaseapp.com',
    storageBucket: 'paceo-f6257.appspot.com', // ✔ FIXED
    measurementId: 'G-CCCZ3VD7RG',
  );
}
